# Generated by jsonapi_crud https://github.com/oncore-education/jsonapi_crud

Dir[Rails.root.join("spec/support/jsonapi_crud/**/*.rb")].each {|f| require f unless f.to_s == __FILE__}

RSpec.configure do |config|
  config.include JsonapiCrud::HttpHelper
  config.include JsonapiCrud::JsonHelper
  config.include JsonapiCrud::ResponseHelper
  config.include JsonapiCrud::JsonResponse
end