# Generated by jsonapi_crud http://github.com

Dir[Rails.root.join("spec/support/jsonapi_crud/**/*.rb")].each {|f| require f unless f.to_s == __FILE__}

RSpec.configure do |config|
  config.extend JsonapiCrud::SharedParams
  config.include JsonapiCrud::SharedParams

  config.include JsonapiCrud::HttpHelper
  config.include JsonapiCrud::JsonHelper
  config.include JsonapiCrud::ResponseHelper
end